### Score: `[105]`

Q1. `[11]` Good job! 

Q2. `[11]` Good job! 

Q3. `[18]` Good job For 3.1! 3.2 请重新审题

Q4. `[27]` Good job! 

Q5. `[38]` Good job! 

# Assignment#1 Dongwei ZHAO SID_12432909

In [194]:
#1 Flowchart
def Print_values(a, b, c):
    if a > b: # T
        if b > c: 
            x = a
            y = b
            z = c
            print(f"x + y - 10z = {x} + {y} - 10*{z} = {x + y - 10 * z}") #T_T
        else: #  b <= c T_F, check if a > c
            if a > c:
                x = a
                y = c
                z = b
                print(f"x + y - 10z = {x} + {y} - 10*{z} = {x + y - 10 * z}") #T_F_T
            else: # a <= c
                x = c
                y = a
                z = b
                print(f"x + y - 10z = {x} + {y} - 10*{z} = {x + y - 10 * z}") #T_F_F
    else: # a <= b F
        if b > c: # F_T
            print('Nothing') #F_T Nothing
        else: #F_F
            # b <= c
            x = c
            y = b
            z = a
            print(f"x + y - 10z = {x} + {y} - 10*{z} = {x + y - 10 * z}") #F_F

#Testing the function
Print_values(10, 5, 1) # T_T
Print_values(10, 5, 6) #T_F_T
Print_values(10, 5, 11) #T_F_F
Print_values(1, 5, 6) #F_F
Print_values(1, 5, 3) #F_T
#Calling the function when a = 10, b = 5, c = 1
Print_values(10, 5, 1)

x + y - 10z = 10 + 5 - 10*1 = 5
x + y - 10z = 10 + 6 - 10*5 = -34
x + y - 10z = 11 + 10 - 10*5 = -29
x + y - 10z = 6 + 5 - 10*1 = 1
Nothing
x + y - 10z = 10 + 5 - 10*1 = 5


In [1]:
#2. Continuous ceiling function
import math

def F(x, memo={1: 1}):
    # Define a dictionary memo to store already calculated values,and given initial value 1:1
    if x not in memo:
        memo[x] = F(math.ceil(x / 3), memo) + 2 * x
    return memo[x]

# Given list with N positive integers
N = [1, 2, 4, 100, 5, 3, 1]

# Calculating F(x) for every element x in the list
results = [F(x) for x in N]

# Printing results
for x, result in zip(N, results):
    print(f'F({x}) = {result}')

F(1) = 1
F(2) = 5
F(4) = 13
F(100) = 305
F(5) = 15
F(3) = 7
F(1) = 1


In [2]:
#3. Dice rolling
#3.1
def find_number_of_ways(num_dice, num_faces, target_sum):
    if target_sum < num_dice or target_sum > num_dice * num_faces: #boundary condition
        return 0

    #dynamically programmed array, dp[i] represents the number of ways that sum i
    dp = [0] * (target_sum + 1)
    dp[0] = 1 #initial value

    # NOTE: 一维数组的dp, perfect !
    
    for _ in range(num_dice):
        #new array to store the results of the current round
        next_dp = [0] * (target_sum + 1)
        #iterate over all the current possible sums s
        for s in range(target_sum + 1):
            #traverse all possible face values of the current die
            for face_value in range(1, num_faces + 1):
                if s + face_value <= target_sum:
                    next_dp[s + face_value] += dp[s] #number of ways to update new sums
        dp = next_dp

    return dp[target_sum]

num_dice = 10
num_faces = 6
target_sum = 35
ways = find_number_of_ways(num_dice, num_faces, target_sum)
print(f'The number of ways to get sum {target_sum} with {num_dice} six-faced dice is: {ways}')

The number of ways to get sum 35 with 10 six-faced dice is: 4395456


In [197]:
#3. Dice rolling
#3.2
# BUG: WHY? 这个 Number_of_ways 是为啥？
Number_of_ways = [(x - 1) // 2 for x in range(10, 61)]

# Find the value(s) of x that yield the maximum number of ways
max_ways = max(Number_of_ways)
max_x_values = [10 + i for i, ways in enumerate(Number_of_ways) if ways == max_ways]

print("Number_of_ways:", Number_of_ways)
print("x values that yield the maximum number of ways:", max_x_values)
print("Maximum number of ways:", max_ways)

Number_of_ways: [4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 25, 26, 26, 27, 27, 28, 28, 29, 29]
x values that yield the maximum number of ways: [59, 60]
Maximum number of ways: 29


In [3]:
#4. Dynamic programming
#4.1
import random

def Random_integer(N):
    #List comprehensions
    return [random.randint(0, 10) for _ in range(N)]

N = 10
result = Random_integer(N)
print(result)

[9, 10, 7, 3, 2, 10, 0, 4, 3, 7]


In [4]:
#4. Dynamic programming
#4.2
import itertools
import numpy as np

def Sum_averages(arr):
    total_sum = 0
    for subset_size in range(1, len(arr) + 1):
        # Get all combinations of elements of the given size
        subsets = itertools.combinations(arr, subset_size)
        # Calculate and add their averages to total_sum
        for subset in subsets:
            total_sum += np.mean(subset)
    return total_sum

arr = [1, 2, 6, 6, 8]
print(Sum_averages(arr))

142.6


In [5]:
#4. Dynamic programming
#4.3
Total_sum_averages = []
arr_list = []#check list
N_range = range(1, 21)
for N in N_range:
    arr = Random_integer(N)
    if N <= 4:  # Output check
        arr_list.append(arr)
    Total_sum_averages.append(Sum_averages(arr))

print(arr_list) # or arr_list[:4] if N <= 4 有点突兀
print( Total_sum_averages[:4])

[[8], [10, 8], [0, 0, 0], [0, 9, 3, 6]]
[np.float64(8.0), np.float64(27.0), np.float64(0.0), np.float64(67.5)]


In [6]:
#4. Dynamic programming
#4.3
# NOTE: recommend to use matplotlib
# proplot 似乎已经停止维护，需要降低matplotlib版本与之适配

import proplot as pplt
fig, ax = pplt.subplots()
ax.plot(range(1, 21), Total_sum_averages, label='Sum of Averages')
ax.format(title='Sum of Averages of Subsets for N from 1 to 100', xlabel='N', ylabel='Total Sum of Averages', titlepad=15)
pplt.show()

AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'

In [10]:
#5. Path counting
#5.1
import random

# 5.1 Create a matrix with N rows and M columns, fill the right-bottom corner and top-left corner cells with 1, and randomly fill the rest of matrix with integer 0 or 1.
def create_matrix(N, M):
    matrix = np.random.randint(0, 2, size=(N, M))
    matrix[0][0] = 1  # Top-left corner
    matrix[N-1][M-1] = 1  # Right-bottom corner
    return matrix

matrix = create_matrix(5, 5)
print(matrix)


[[1 0 1 1 0]
 [0 1 1 0 0]
 [1 1 0 0 1]
 [0 0 0 1 0]
 [1 1 0 0 1]]


In [18]:
#5. Path counting
#5.2
def Count_path(matrix):
    N, M = matrix.shape
    # Create a DP array to store the number of paths.
    dp = np.zeros((N, M), dtype=int)

    # Initialize the starting point
    dp[0, 0] = 1

    # Fill the DP table
    for i in range(N):
        for j in range(M):
            if matrix[i, j] == 1:
                if i > 0:
                    dp[i, j] += dp[i - 1, j]
                if j > 0:
                    dp[i, j] += dp[i, j - 1]

    return dp[N - 1, M - 1]
matrix = create_matrix(5, 5)
print(matrix)
print(Count_path(matrix))

[[1 1 0 0 1]
 [1 0 0 0 0]
 [1 0 1 0 1]
 [1 1 0 1 1]
 [1 1 0 1 1]]
0


In [21]:
#5. Path counting
#5.3
N, M = 10, 8
runs = 1000
total_paths = 0
for _ in range(runs):
    #Call create_matrix function
    matrix = create_matrix(N, M)

    ##Call Count_path function
    total_paths += Count_path(matrix)

# Calculate the mean number of paths
mean_paths = total_paths / runs
print(f"Mean number of paths from {runs} runs: {mean_paths}")

Mean number of paths from 1000 runs: 0.206
